### ISSUE TITLE
NoELM detected on OS Layer with App Layering 2003 on W2K16 and W2K19

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#251]
"NoELM" is detected on an W2K16 or W2K19 OS Layer with App Layering 2003.

[PREP_BISF_WPT_CITRXAL360000_20200616-122817.log](https://github.com/EUCweb/BIS-F/files/4787205/PREP_BISF_WPT_CITRXAL360000_20200616-122817.log)
[PREP_BISF_WPT_CITRXAL360000_20200616-144732.log](https://github.com/EUCweb/BIS-F/files/4787206/PREP_BISF_WPT_CITRXAL360000_20200616-144732.log)
[PREP_BISF_CITRXAL360000_20200616-144732.log](https://github.com/EUCweb/BIS-F/files/4787207/PREP_BISF_CITRXAL360000_20200616-144732.log)
[PREP_BISF_CITRXAL9d8005_20200616-144347.log](https://github.com/EUCweb/BIS-F/files/4787208/PREP_BISF_CITRXAL9d8005_20200616-144347.log)
[PREP_BISF_WPT_CITRXAL9d8005_20200616-144347.log](https://github.com/EUCweb/BIS-F/files/4787209/PREP_BISF_WPT_CITRXAL9d8005_20200616-144347.log)
[PREP_BISF_CITRXAL360000_20200616-122817.log](https://github.com/EUCweb/BIS-F/files/4787210/PREP_BISF_CITRXAL360000_20200616-122817.log)

**Comment by matthias-schlimm** [comment]
### please change as described and test again
**Note: this will not fix the issue, only debugging to see where the issue come from. Please change the code, run again and upload the new logs**

**Script:**  BISF.psm1 
**Function:** Test-AppLayeringSoftware
**Line:** remove 2579 - 2583 and insert below the new code

**new:**

```
Write-BISFLog -Msg "Debug Only: OverrideRunMode ist set to $OverrideRunMode value" -ShowConsole -Color Magenta
IF (($DiskMode -eq "ReadWriteAppLayering") -or ($svcSatus -ne "Running")) {$OverrideRunMode = $true}
Write-BISFLog -Msg "Debug Only: OverrideRunMode ist set to $OverrideRunMode value" -ShowConsole -Color Magenta
IF (($UPL -eq $true ) -and ($DiskMode -eq "VDAPrivateAppLayering")) {$OverrideRunMode = $true}
Write-BISFLog -Msg "Debug Only: OverrideRunMode ist set to $OverrideRunMode value" -ShowConsole -Color Magenta
$DomainMember = (Get-WmiObject -Class Win32_ComputerSystem).PartOfDomain
Write-BISFLog -Msg "Computer is DomainMember: $DomainMember"
IF (($DomainMember -eq $true ) -and ($CTXAppLayeringRunMode -ne 1)) { $OverrideRunMode = $false } ELSE {$OverrideRunMode = $true }
Write-BISFLog -Msg "Debug Only: OverrideRunMode ist set to $OverrideRunMode value" -ShowConsole -Color Magenta
```

### Preview of the changes:
**before:**
![image](https://user-images.githubusercontent.com/34108484/84818461-d35bcf80-b016-11ea-94a0-31e5e2fb6892.png)


**after:**
![image](https://user-images.githubusercontent.com/34108484/84818339-a4ddf480-b016-11ea-83c1-553066eb386a.png)

**Comment by thewitscher** [comment]
here are the new W2K19 Logs with the above code changes:
[PREP_BISF_CITRXAL9d8005_20200617-105202.log](https://github.com/EUCweb/BIS-F/files/4791344/PREP_BISF_CITRXAL9d8005_20200617-105202.log)
[PREP_BISF_WPT_CITRXAL9d8005_20200617-105202.log](https://github.com/EUCweb/BIS-F/files/4791345/PREP_BISF_WPT_CITRXAL9d8005_20200617-105202.log)

**Comment by matthias-schlimm** [comment]
**Computer is not a DomainMember**
this is the initiator for Override the RunMode, I will have a look to it 

```
17.06.2020 10:52:36 | Administrator | INFORMATION... | Debug Only: OverrideRunMode ist set to False value
17.06.2020 10:52:36 | Administrator | INFORMATION... | Computer is DomainMember: False
17.06.2020 10:52:36 | Administrator | INFORMATION... | Debug Only: OverrideRunMode ist set to True value
17.06.2020 10:52:36 | Administrator | INFORMATION... | The original App Layering RunMode ist set to 3, based on the DiskMode UnmanagedAppLayering the RunMode is internally changed to 1 to get the right layer
17.06.2020 10:52:36 | Administrator | INFORMATION... | Citrix AppLayering - No-ELM detected

```

**Comment by thewitscher** [comment]
Please check this also for the App Layer, because the App Layered Packaged VM is also not a DomainMember. Only the Platform Layered VM is domain joined.

**Comment by matthias-schlimm** [comment]
In summary for the Script

**OS-Layer:** 
RunMode: 3
DomainMember: $false
UniService: running
Windows 10 -> UPL: $false (If $true: UPL inside Applayering PackagingVM make no sense)
Server OS -> UPL: $false
DiskMode:  UnmanagedAppLayering

**Platform-Layer:**
RunMode: 4
DomainMember: $true
UniService: running
Windows 10 -> UPL: $false (If $true: UPL inside Applayering PackagingVM make no sense)
Server OS -> UPL: $false
DiskMode:  VDAPrivateAppLayering

**Application Layer:**
RunMode: 4
DomainMember: $false
UniService: running
Windows 10 -> UPL: $false (If $true: UPL inside Applayering PackagingVM make no sense)
Server OS -> UPL: $false
DiskMode: UnmanagedAppLayering

**Outside-ELM:**
RunMode: 1
DomainMember: _$false/$true ?_
UniService: stopped
Windows 10 -> UPL: $true
Server OS -> UPL: $false
DiskMode: ReadWriteAppLayering

**Comment by thewitscher** [comment]
Hi Matthias,
I just checked the Layering services on a W10 VDI with UPL Feature with the following states:
uniservice = running, starttype=disabled
ulayer = running, starttype=auto
upl-support = running, starttype= auto

**Comment by thewitscher** [comment]
in a layered VM (with ELM) only one App Layering Service exists with the following state:
uniservice = running, starttype=auto

**Comment by matthias-schlimm** [comment]
UPL Support detection in 7.1912.3 and earlier works as follows:

```
$Global:UPL = $false
$CheckVersion = "7.24" # VDA 1912  with UPL support
IF ($VDAVersion -ge $CheckVersion){
  Write-BISFLog "VDA Version $VDAVersion supports User Personalization Layer (UPL).. check if the UPL Services are installed" -ShowConsole -Color DarkCyan -SubMsg
  $UPLsvc1 = Test-BISFService -ServiceName "upl-Support" -ProductName "Citrix UPL Support Service"
  $UPLsvc2 = Test-BISFService -ServiceName "ulayer" -ProductName "Citrix Layering Service"
  IF (($UPLsvc1 -eq $true) -and ($UPLsvc2 -eq $true)) {
    $Global:UPL = $true
    Write-BISFLog "UPL Services are installed" -ShowConsole -Color DarkCyan -SubMsg
  } ELSE {
    Write-BISFLog "UPL Services are NOT installed"
  }
} ELSE {
  Write-BISFLog "VDA version $VDAVersion does NOT support User Personalization Layer (UPL)"
}

```

**Comment by matthias-schlimm** [comment]
I will complete rewritten the function to detect the right layer

**Comment by matthias-schlimm** [comment]
### Action plan

Script: BISF.psm1
Function: Test-AppLayerungSoftware
Line: Delete Line 2529 - 2613 (complete function Test-AppLayeringSoftware)

Replace it with the code inside the attached file

[function Test-AppLayeringSoftware.txt](https://github.com/EUCweb/BIS-F/files/4797581/function.Test-AppLayeringSoftware.txt)


Test all different modes with the code changes above, this will also address your HF https://github.com/EUCweb/BIS-F/issues/248

**Comment by thewitscher** [comment]
cannot use the checkbox.
 
Server 2016/2019 - VDA without AppLayering - works fine

Logs:
[PREP_BISF_MASTER-W2K19_20200618-092053.log](https://github.com/EUCweb/BIS-F/files/4797003/PREP_BISF_MASTER-W2K19_20200618-092053.log)
[PREP_BISF_MASTER-W2K16_20200618-092541.log](https://github.com/EUCweb/BIS-F/files/4797004/PREP_BISF_MASTER-W2K16_20200618-092541.log)
_________________________________________________________________________________________________
Windows 10 - VDA with UPL - OS Layer detected - doesn´t work

Logs:
[PREP_BISF_WPT_MASTER-W10EX64_20200618-093247.log](https://github.com/EUCweb/BIS-F/files/4797046/PREP_BISF_WPT_MASTER-W10EX64_20200618-093247.log)
[PREP_BISF_MASTER-W10EX64_20200618-093247.log](https://github.com/EUCweb/BIS-F/files/4797047/PREP_BISF_MASTER-W10EX64_20200618-093247.log)

**Comment by matthias-schlimm** [comment]
### Action Plan
**Script:** BISF.sp1
**Line:** 356-357
**Action:** switch the 2 lines as shown below

**before:**
```
$Global:returnTestAppLayeringSoftware = Test-BISFAppLayeringSoftware -Verbose:$VerbosePreference
$Global:returnTestXDSoftware = Test-BISFXDSoftware -Verbose:$VerbosePreference
```


**after:**
```
$Global:returnTestXDSoftware = Test-BISFXDSoftware -Verbose:$VerbosePreference
$Global:returnTestAppLayeringSoftware = Test-BISFAppLayeringSoftware -Verbose:$VerbosePreference
```
	
**Description:**
The Variable $UPL will be defined in Test-XDSoftware and processed in Test-AppLayeringSoftware

**Comment by thewitscher** [comment]
Server 2016/2019 - VDA with AppLayering

    OS - Layer: works fine

Logs:
[PREP_BISF_CITRXAL360000_20200618-085846.log](https://github.com/EUCweb/BIS-F/files/4797102/PREP_BISF_CITRXAL360000_20200618-085846.log)
[PREP_BISF_CITRXAL9d8005_20200618-094801.log](https://github.com/EUCweb/BIS-F/files/4797103/PREP_BISF_CITRXAL9d8005_20200618-094801.log)

**Comment by thewitscher** [comment]
Windows 10 - VDA with UPL - noELM detected: works fine, but the warning message is wrong!
You should delete the comment after ","

Logs:
[PREP_BISF_MASTER-W10EX64_20200618-100002.log](https://github.com/EUCweb/BIS-F/files/4797182/PREP_BISF_MASTER-W10EX64_20200618-100002.log)

**Comment by matthias-schlimm** [comment]
update the script above and remove the warning message. Log output much better than before


Processing function Test-BISFService
Service UniService exists
Product Citrix AppLayering (Version 19.11.0.13-b3cedcc) installed
**OverrideRunMode: False**
**Citrix AppLayering RunMode: 3**
Processing function Get-BISFDiskMode
DiskMode is VDAPrivateAppLayering
DiskMode: VDAPrivateAppLayering
Processing function Test-BISFServiceState
The Service Citrix App Layering Guest Service is successfully in Running state
ServiceStatus Citrix AppLayering: Running
**DomainMember: True**
**UPL: True**
**OverrideRunMode: True**
The original Citrix AppLayering RunMode ist set to 3, based on the DiskMode VDAPrivateAppLayering the RunMode is internally changed to 1 to get the right layer
**Citrix AppLayering - No-ELM detected**

**Comment by matthias-schlimm** [comment]
update the code again as follows:

[function Test-AppLayeringSoftware.txt](https://github.com/EUCweb/BIS-F/files/4797888/function.Test-AppLayeringSoftware.txt)

**Comment by thewitscher** [comment]
done.
run´s like a charm :)

Logs:
[PREP_BISF_MASTER-W10EX64_20200618-121953.log](https://github.com/EUCweb/BIS-F/files/4797979/PREP_BISF_MASTER-W10EX64_20200618-121953.log)

**Comment by thewitscher** [comment]
Server 2016/2019 - VDA with AppLayering

Platform - Layer: works fine

Logs:
[PREP_BISF_W2K16-PL-MCS_20200618-130821.log](https://github.com/EUCweb/BIS-F/files/4798667/PREP_BISF_W2K16-PL-MCS_20200618-130821.log)
[PREP_BISF_W2K19-PL-MCS_20200618-135718.log](https://github.com/EUCweb/BIS-F/files/4798668/PREP_BISF_W2K19-PL-MCS_20200618-135718.log)

**Comment by thewitscher** [comment]
Server 2016/2019 - VDA with AppLayering

Application - Layer: works fine

Logs:
[PREP_BISF_CITRXAL758001_20200618-153059.log](https://github.com/EUCweb/BIS-F/files/4799398/PREP_BISF_CITRXAL758001_20200618-153059.log)
[PREP_BISF_CITRXALcf8002_20200618-163055.log](https://github.com/EUCweb/BIS-F/files/4799399/PREP_BISF_CITRXALcf8002_20200618-163055.log)

**Comment by thewitscher** [comment]
Server 2016/2019 - VDA with AppLayering

Outside ELM (published layered Image) - Layer: works, but with a warning, NoELM detected is fine

The warning message should be something different.

Logs:
[PREP_BISF_W2K16-PL-MCS_20200618-161812.log](https://github.com/EUCweb/BIS-F/files/4799414/PREP_BISF_W2K16-PL-MCS_20200618-161812.log)
[PREP_BISF_W2K19-PL-MCS_20200618-165925.log](https://github.com/EUCweb/BIS-F/files/4799415/PREP_BISF_W2K19-PL-MCS_20200618-165925.log)

**Comment by matthias-schlimm** [comment]
I will use "Published image" this is the right wording from Citrix Documentation too, but remember this will be used for UPL as well. 
checkout [[HOW TO] Citrix AppLayering in a dynamic Environment](https://eucweb.com/kba/2312191033-2)

**Comment by matthias-schlimm** [comment]
**Use checkbox if it works as expected, otherwise write a comment below**
**Upload all BIS-F logs from each Test**
- [x] Windows 10 - VDA without UPL in Azure (non Domain) [PREP_BISF_BaseImage_20200618-213349.log](https://github.com/EUCweb/BIS-F/files/4801321/PREP_BISF_BaseImage_20200618-213349.log)
- [x] Windows 10 - VDA with UPL [PREP_BISF_MASTER-W10EX64_20200618-121953.log](https://github.com/EUCweb/BIS-F/files/4798044/PREP_BISF_MASTER-W10EX64_20200618-121953.log)
- [x] Server 20162/019 - VDA without AppLayering [PREP_BISF_MASTER-W2K19_20200618-092053.log](https://github.com/EUCweb/BIS-F/files/4798130/PREP_BISF_MASTER-W2K19_20200618-092053.log)
- Server 2016/2019 - VDA with AppLayering
     - [x] OS - Layer [PREP_BISF_CITRXAL360000_20200618-085846.log](https://github.com/EUCweb/BIS-F/files/4798132/PREP_BISF_CITRXAL360000_20200618-085846.log)
     - [x] Platform - Layer [PREP_BISF_W2K16-PL-MCS_20200618-130821.log](https://github.com/EUCweb/BIS-F/files/4798982/PREP_BISF_W2K16-PL-MCS_20200618-130821.log)
     - [x] Application - Layer [PREP_BISF_CITRXAL758001_20200618-153059.log](https://github.com/EUCweb/BIS-F/files/4799892/PREP_BISF_CITRXAL758001_20200618-153059.log)
     - [x] Outside-ELM _(published image -> boot in private or read/write Mode and running BIS-F preparation)_ 
[PREP_BISF_W2K16-PL-MCS_20200618-161812.log](https://github.com/EUCweb/BIS-F/files/4799903/PREP_BISF_W2K16-PL-MCS_20200618-161812.log)

**Comment by matthias-schlimm** [comment]
all tests passed, see above

codechanges integrated into developer branch

**Comment by thewitscher** [comment]
Windows 10 - VDA without UPL: works fine

Logs:
[PREP_BISF_MASTER-W10E_20200620-202844.log](https://github.com/EUCweb/BIS-F/files/4808421/PREP_BISF_MASTER-W10E_20200620-202844.log)
